---

- name: apt install packages
  become: yes
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - language-pack-en
    - build-essential
    - python3-setuptools
    - python3-pip
    - python3-smbus
    - python3-dev
    - libbz2-dev
    - libc6-dev
    - libdb5.3-dev
    - libexpat1-dev
    - libffi-dev
    - libgdbm-dev
    - liblzma-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - openssl
    - tk-dev
    - zlib1g-dev

- name: add pyenv config to shell rc file
  lineinfile:
    line: "{{item}}"
    path: "{{shell_rc}}"
  with_items:
    - export PATH="/home/vagrant/.pyenv/bin:$PATH"
    - eval "$(pyenv init -)"
    - eval "$(pyenv virtualenv-init -)"

- name: set fact for pyenv_executable
  set_fact:
    pyenv_executable: "{{ansible_env.HOME}}/.pyenv/bin/pyenv"

- name: stat pyenv_executable
  stat:
    path: "{{pyenv_executable}}"
  register: stat_task

- name: download pyenv-installer script
  get_url:
    url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
    dest: /tmp/pyenv-installer
    mode: 0555
  when: stat_task.stat.exists != true

- name: run pyenv-installer script with user shell
  command: /tmp/pyenv-installer
  when: stat_task.stat.exists != true

- name: pyenv update
  command: "{{pyenv_executable}} update"
  when: stat_task.stat.exists == true

- name: pyenv versions
  command: "{{pyenv_executable}} versions"
  register: pyenv_versions_task
  ignore_errors: yes

- name: pyenv install required python version
  command: "{{pyenv_executable}} install {{python_version}}"
  when: python_version not in pyenv_versions_task.stdout

- name: pyenv create virtualenv if required
  command: >
    {{pyenv_executable}} virtualenv
    {{python_version}} {{virtualenv_name}}
  when:
    - virtualenv_name is defined
    - virtualenv_name not in pyenv_versions_task.stdout

- name: copy requirements file to server if provided
  copy:
    src: "{{requirements_path}}"
    dest: "/tmp/requirements.txt"
  when:
    - requirements_path is defined
  tags: requirements

- name: set fact for virtualenv_root
  set_fact:
    virtualenv_root: "{{ansible_env.HOME}}/.pyenv/versions"

- name: install requirements in virtualenv if required
  command: >
    {{virtualenv_root}}/bin/pip
    install -U -r /tmp/requirements.txt
  when:
    - virtualenv_name is defined
    - requirements_path is defined
  tags: requirements
